### ISSUE TITLE
Adjusting Twin for 100s of Clusters? 

### ISSUE THREAD

**Issue by MohammadVahidiPro** [Yunfan-Li/Twin-Contrastive-Learning#25]
I'm very interested in your work, and I wanted to try your model on other datasets. But running the code on datadets with many clusters (like 89 or 152 classes) results in high NMI but relatively low ACC. I find it strange for accuracy to be 30-40% lower than NMI. NMI is near state of the art yet ACC is way behind other models. I'm not sure what am I doing wrong. Do you have any idea what's causing this and how can I fix it? maybe some adjustments to CCH/ICH? or a problem with cluster assignment mechanism? 
I'm new to this field so I'm having trouble finding the exact cause of this discrepancy between NMI and ACC and improving the model. I would appreciate any help and suggestions that could help me use this great model for datasets with very large number of classes. 

ps: for googlenews_TS dataset with 152 clusters I set 152 dimension for CCH head and 256 for ICH. 

(excuse my English)

**Comment by Yunfan-Li** [comment]
According to your description, I guess it is due to the batch size. Considering a batch of 256 samples which belongs to 152 classes, there would be less than 2 samples per class on average within the batch. Some classes would even be absent in the batch. In this case, the CCH loss could no longer catch the cluster characteristics which would lead to inferior performance.

To save the gpu memory, you may take a look at strategies such as mix precision.

**Comment by MohammadVahidiPro** [comment]
thanks for your fast response.
